"""Global RNG seeding for reproducible train-from-scratch runs (§6).

The agent's ε-greedy and the replay buffer's sampling already draw from an
injected, seeded NumPy ``Generator``. The one remaining source of run-to-run
variation is the network's *weight initialisation*, which draws from the global
Torch RNG. Seeding Python / NumPy / Torch here makes a fresh training run
reproducible bit-for-bit on a given machine, so the README's reported numbers
can be regenerated by anyone with the repo.
"""

from __future__ import annotations

import random

import numpy as np
import torch


def seed_everything(seed: int | None) -> None:
    """Seed the Python, NumPy and Torch global RNGs (no-op when ``seed`` is None)."""
    if seed is None:
        return
    seed = int(seed)
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
